### ISSUE TITLE
find_by_zipcode missing 8628 Trenton, NJ

### ISSUE THREAD

**Issue by Johnsalzarulo** [farski/TZip#11]
Steps to reproduce

````
pry(main)> ActiveSupport::TimeZone.find_by_zipcode('8628')
=> nil
````

Expected behavior
````
pry(main)> ActiveSupport::TimeZone.find_by_zipcode('8628')
=> "Eastern Time (US & Canada)"
````

Actual behavior
````
pry(main)> ActiveSupport::TimeZone.find_by_zipcode('8628')
=> nil
````

System configuration

**Rails version:** Rails 5.0.6
**Ruby version:** ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin16]

**Comment by mattjohnsonpint** [comment]
I think the issue here is that you forgot the leading 0. Zip codes are 5 digit strings.  ('08628')

**Comment by Johnsalzarulo** [comment]
Thanks so much! So sorry to waste your time!
